version: '3'
services:

  workspace:
    build:
      context: ./docker/workspace
      args:
        - PUID=${DOCKER_UID:-1000}
        - PGID=${DOCKER_GID:-1000}
    # environment:
    #     DB_HOST: database
    #     DB_PORT: 3306
    volumes:
      - .:/var/www/
    # depends_on:
    # - database
    # links:
    # - database
    tty: true
