service:
  name: warmup-test

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters

custom:
  currentStage: ${opt:stage, self:provider.stage}
  base-name: ${self:service}-${self:custom.currentStage}

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: dev
  timeout: 10

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
      - Fn::Join:
        - ':'
        - - arn:aws:lambda
          - Ref: AWS::Region
          - Ref: AWS::AccountId
          - function:${self:service}-${opt:stage, self:provider.stage}-*

functions:
  test:
    handler: handlers/test.handler

  warmup:
    handler: handlers/warmup.handler
